export const SHOW_USERDATA = 'SHOW_USERDATA';
export const LOADING_USERDATA = 'LOADING_USERDATA';
export const FAILED_USERDATA = 'FAILED_USERDATA';
export const ADDBOOKING_CONSULTATION = 'ADDBOOKING_CONSULTATION';